# Generated by Django 4.0.5 on 2022-06-05 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestructure',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents_file', to='filesystem.filestructure'),
        ),
        migrations.AlterField(
            model_name='filestructure',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='childs_file', to='filesystem.filestructure'),
        ),
    ]
